### PR TITLE
Restrict contraceptive uptake to sexually active agents 

### PR DESCRIPTION
**Pull request by avictorious**
This PR is the algorithm changes necessary to track sexual inactivity in agents and then select agents as eligible to start contraceptive methods based on whether they've gotten to age of sexual debut and have been sexually active within the last 12 months.   It adds a testing script under a new folder "analyses" to query the model for these characteristics.

The sexual activity tracker is ingrained in the model and the restriction can be turned on and off with a new boolean "restrict_method_use" in the location.py parameters files.  It is set to be off.  It should be turned on when matrices are substituted to be contraceptive method uptake only among women who have ever had sex and have had sex in the last 12 months. 

Closes issue #145.  Note that as requested by @MObrien-IDM, there is a very small non-zero chance that someone may take up a method before they debut (they are eligible at fated debut age, not just when they debut), but as the algorithm is written there is a zero chance they will take up a method if they have not had sex in >= 12 months.

CPR and other calibration targets for Senegal and Kenya will need to be queried again once matrices are swapped out.

### Type(s) of change
- [ ] Bugfix
- [X] Refactor
- [ ] New feature
- [ ] Other

### Checklist
- My code follows the [style guide](https://github.com/amath-idm/styleguide)
  - [X] Yes
  - [ ] N/A
- I've commented my code
  - [X] Yes
  - [ ] N/A
- I've incremented the version number
  - [X] Yes
  - [ ] N/A
- I've updated the changelog
  - [X] Yes
  - [ ] N/A
- I've added tests and checked code coverage
  - [X] Yes
  - [ ] N/A

### CODE REVIEW

**Comment by avictorious** [comment]
@cliffckerr I'm getting the same pytest errors that Michelle was getting previously.  I think there's some backend infrastructure work unrelated to my code changes here that needs to be addressed for this to be able to pass.... 

FAILED test_analyzers.py::test_timeseries_recorder - ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (100,) + inhomogeneous part.

**Comment by cliffckerr** [comment]
@avictorious This was caused by hard-coding keys in `timeseries_recorder()`, @emilykclaps were able to fix it this afternoon though!

**Review by cliffckerr — APPROVED** [review]
Looks good!

**Review by MObrien-IDM — APPROVED** [review]
Thank you @avictorious for this! Thank you @emilykclaps and @cliffckerr for fixing the bug! Appreciate you all.

**Comment by avictorious** [comment]
@emilykclaps @cliffckerr thanks for addressing the bug!  @MObrien-IDM Glad this request got to completion, it's a nice addition.

**Pull request merged**
