### PR TITLE
Issue310

### PR DESCRIPTION
**Pull request by emilydriano**
### Brief description
Addresses issue #310 , which was to remove the legacy 'use_subnational' feature logic (as we implemented each region as its own specific location so that you can run a multisim with one sim per region). 

### Type(s) of change
- [ ] Bugfix
- [ X ] Refactor
- [ ] New feature
- [ ] Other

### Checklist
- My code follows the [style guide](https://github.com/amath-idm/styleguide)
  - [ X ] Yes
  - [ ] N/A
- I've commented my code
  - [ X ] Yes
  - [ ] N/A
- I've incremented the version number
  - [ X ] Yes
  - [ ] N/A
- I've updated the changelog
  - [ X ] Yes
  - [ ] N/A
- I've added tests and checked code coverage
  - [ X ] Yes
  - [ ] N/A

### CODE REVIEW

**Comment by emilydriano** [comment]
@MObrien-IDM is this okay to merge into main?

**Review by pausz — APPROVED** [review]
Looks ok to me.

**Comment by pausz** [comment]
housekeeping: ok to merge this branch @emilydriano @MObrien-IDM?

**Comment by emilydriano** [comment]
> housekeeping: ok to merge this branch @emilydriano @MObrien-IDM?

yes ok by me!

**Review by MObrien-IDM — APPROVED** [review]

**Pull request merged**
