### PR TITLE
Empowerment develop psl

### PR DESCRIPTION
**Pull request by pausz**
### Brief description
Sending a draft PR with new attributes and education dynamics. It'd be great to hear your thoughts and feedback on these new additions! 

This branch implements new empowerment attributes based on the analysis plan (#170),  implements some (temporary) default initialisation strategies for these new attributes (#172), and update rules for education progression  (#171). 
  

Some questions:
+ How much detail do we want to incorporate into education dynamics? Do we model permanent disruptions, temporary interruptions, resumptions? I've implemented a few basic functions that would enable us to have such functionality. 

+ Do we seek to match current DHS education and literacy statistics (eg, proportion of women between 15-49 who have  more than secondary education)?   

+ The `relationship_status` attribute has not been initialised yet. I was wondering if we want this attribute to be categorical anb support values such as `["single", "married", "divorced", "widowed"]` or simply a boolean attribute `married` would be enough to begin with.

+ What attributes should be initialised from location-specific population distributions (like age and sex)? Which attributes will be initialised with the same strategy across locations?  

+ I've added a new attribute called `partnership_formation_age`. But I'm wondering if this should be a parameter like `debut_age` ?

### Type(s) of change
- [ ] Bugfix
- [ ] Refactor
- [x] New feature
- [ ] Other

### Checklist
- My code follows the [style guide](https://github.com/amath-idm/styleguide)
  - [x] Yes
  - [ ] N/A
- I've commented my code
  - [x] Yes
  - [ ] N/A
- I've incremented the version number
  - [ ] Yes
  - [x] N/A
- I've updated the changelog
  - [ ] Yes
  - [x] N/A
- I've added tests and checked code coverage
  - [ ] Yes
  - [x] N/A

### CODE REVIEW

**Comment by mzimmermann-IDM** [comment]
Thank you for all the work on this @pausz ! It's looking great. I have been thinking more about education and I think we should actually take a slightly different approach than I proposed before. Instead of having an education target, I think we can just use a probability of getting one more year of education each year. Each year on her birthday, the woman will either get one more year of education incremented or not. And the probability of that happening will be based on age and parity. For example: For a girl 15yo who has 6 years of education and parity 0, there is a xx% probability of having 7+ years of edu at age 16. I can pull a matrix from DHS that shows, by age and parity, the percentage that have each number of years of education. The DHS data will only start at age 15, so we will have to find a way to work backwards and recreate the years from start of edu to age 15. Does this approach make sense to you? We can talk through it more in our next meeting, and I will also pull the data before that to see what it looks like.

**Comment by MObrien-IDM** [comment]
> For relationship status, I was thinking we would just have 'partnered' as a boolean. We want to be able to capture the dynamic in a relationship, but I don't think we have enough data to differentiate between married or other long term partnership, or between single, divorced, and widowed. @MObrien-IDM what do you think?

Yes - We won't have enough data to distinguish (and may not want to anyway, as I'm not sure we can make a qualitative distinction between women who, all else equal, are divorced or single). Partnered vs. unpartnered is a good idea.

**Comment by pausz** [comment]
Closing this draft PR. The information in this discussion  has been moved to the relevant issues:
- #170 
- #171  
- #172

**Comment by pausz** [comment]
- Rather than deleting the branch `empowerment-develop-psl`, I  renamed (moved) it to `_deprecated-empowerment-develop-psl`.

- If you had checked out `empowerment-develop-psl` locally, then you can do:
```
git branch -m empowerment-develop-psl _deprecated_empowerment-develop-psl
git fetch origin
git branch -u origin/_deprecated_empowerment-develop-psl _deprecated_empowerment-develop-psl
git remote set-head origin -a
```
These steps are optional to avoid having a local branch that tracks a non-existing remote branch.

**Pull request closed without merging**
