### PR TITLE
Empowerment se decisionhealth

### PR DESCRIPTION
**Pull request by pausz**
### Brief description
This PR incorporates: 

+ new empowerment attribute `decision_health` 
+  the standard error columns in empowerment.csv  to initialise empowerment parameters (`kenya.py`) 

It'd be great to know how the initialisation of empowerment metrics based on mean and standard error interact with calibration workflows. To generate different estimates of empowerment parameters and capture data uncertainty,  in `kenya.py`,  the function `empowerment_distributions` now needs to receive a seed. 

Multiple estimates of empowerment parameters generated with different seeds:
Screenshot from 2023-11-02 06-52-29

### Type(s) of change
- [ ] Bugfix
- [ ] Refactor
- [x] New feature
- [ ] Other

### Checklist
- My code follows the [style guide](https://github.com/amath-idm/styleguide)
  - [x] Yes
  - [ ] N/A
- I've commented my code
  - [x] Yes
  - [ ] N/A
- I've incremented the version number
  - [ ] Yes
  - [x] N/A
- I've updated the changelog
  - [ ] Yes
  - [ ] N/A
- I've added tests and checked code coverage
  - [ ] Yes
  - [ ] N/A

### CODE REVIEW

**Comment by pausz** [comment]
@robynstuart I forgot to mention that we have a 5 parameter logistic function in utils.py, and we were considering using that for interpolating and extrapolating data. @mzimmermann-IDM: perhaps we should go ahead and use the logistic function instead of piecewise linear interpolation?

**Comment by mzimmermann-IDM** [comment]
I’m fine with using the logistic function. It should give the same results, right? Will it work only on binary outcomes?

**Comment by pausz** [comment]
@mzimmermann-IDM Ok, I'll play around and see how the interpolated metrics look using the logistic function. I think  it may may provide a better approximation to the input data in empowerment.csv, compared to the piecewise linear.  It would work for all empowerment metrics.

**Comment by pausz** [comment]
@mzimmermann-IDM Results with logistic-based regression :smile:    
Screenshot from 2023-11-03 12-55-16

**Comment by mzimmermann-IDM** [comment]
This looks great! Way better than the other way :)

**Comment by emilydriano** [comment]
@pausz, my sincere apologies for the delay in responding to this. The question on calibration is a good one. I see that there's a default of the seed being set to 42, correct? I think the calibration workflow wouldn't be affected by the incorporation of a seed as long as the resulting paid employment data (in the empowerment_dict), for example, is consistent with each simulation…I would just use this same default seed in my calibration function for this empowerment data target. 

In the calibration class, many simulations are run to identify the optimal free parameters that result in target parameters that are as close as possible to the country data. So I believe incorporating the standard error values add variability to the country (target) data the calibration would try to reproduce (a moving target, so to speak). Thus I'm not sure the best way to account for this in the calibration workflow. An idea would be to just use the mean values and run a regression using the seed aforementioned and then use this as the target in the calibration? Or perhaps there's a better way to account for this uncertainty…curious to hear if @MObrien-IDM or @mzimmermann-IDM have thoughts on this?

**Review by mzimmermann-IDM — APPROVED** [review]
Looks good!

**Pull request merged**
